"""Email delivery via Resend HTTPS API."""
from __future__ import annotations

import base64
import logging
import os
from pathlib import Path

log = logging.getLogger(__name__)


_HTML_TEMPLATE = """<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>{subject}</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
         max-width: 720px; margin: 24px auto; padding: 0 16px; color: #1a1a1a;
         line-height: 1.55; }}
  h1 {{ font-size: 22px; border-bottom: 2px solid #eaeaea; padding-bottom: 8px; }}
  h2 {{ font-size: 17px; margin-top: 28px; color: #0b3d91; }}
  h3 {{ font-size: 14px; color: #555; margin: 6px 0 0; font-weight: 600; }}
  a  {{ color: #0b5fff; text-decoration: none; }}
  a:hover {{ text-decoration: underline; }}
  blockquote {{ border-left: 3px solid #ddd; margin: 8px 0; padding: 2px 12px; color: #555; }}
  .footer {{ margin-top: 32px; padding-top: 12px; border-top: 1px solid #eaeaea;
             font-size: 12px; color: #888; }}
</style>
</head>
<body>
{body}
<div class="footer">Generated by security-summary. Audio attached as MP3.</div>
</body></html>
"""


def render_html(markdown_text: str, subject: str) -> str:
    from markdown_it import MarkdownIt
    md = MarkdownIt("commonmark", {"breaks": True, "linkify": True})
    body = md.render(markdown_text)
    return _HTML_TEMPLATE.format(subject=subject, body=body)


def send(subject: str, html: str, mp3_path: Path | None) -> dict:
    """Send via Resend. Returns the API response dict."""
    import resend  # lazy import

    resend.api_key = os.environ["RESEND_API_KEY"]
    payload: dict = {
        "from": os.environ.get("EMAIL_FROM", "Security Digest <onboarding@resend.dev>"),
        "to": [os.environ["RECIPIENT_EMAIL"]],
        "subject": subject,
        "html": html,
    }
    if mp3_path and mp3_path.exists():
        with open(mp3_path, "rb") as f:
            content = base64.b64encode(f.read()).decode("ascii")
        payload["attachments"] = [{"filename": mp3_path.name, "content": content}]
    resp = resend.Emails.send(payload)
    log.info("email.sent id=%s", resp.get("id") if isinstance(resp, dict) else resp)
    return resp if isinstance(resp, dict) else {"raw": str(resp)}
